---
title: "Same Cue vs Semantic Associate Retrieval Practice"
author: "William Hopper"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.width = 9,
                      cache = TRUE)
options(mc.cores = parallel::detectCores())
library(dplyr)
library(stringdist)
library(tibble)
library(ggplot2)
library(gridExtra)
library(tidyr)
library(whoppeR)
library(afex)
library(bindrcpp)
library(rstanarm)
library(kableExtra)
library(magrittr)
source("../R/test_tidying.R")
```

```{r reading}
oldwd <- setwd("../data-raw")

# Lists/condition assignment table
conditions <-  read.csv("lists.csv", stringsAsFactors = FALSE) %>%
  rename(practice_cue_type = cue_type) %>%
  mutate(practice_cue_type = replace(practice_cue_type,
                                     which(practice == "N"),
                                     NA_character_))

## Group assignment table
subjects <- read.csv("participants.csv", stringsAsFactors = FALSE)

column_types <- c("integer","integer","integer", "integer", "integer",
                  "character", "character", "numeric", "integer", "numeric",
                  "numeric", "numeric", "numeric", "character")
# Test Practice
test_practice_raw <- read.csv("test_practice.csv", stringsAsFactors = FALSE,
                              na.strings = "", colClasses = column_types) %>%
  mutate(recalled = as.logical(recalled))

# Final Test
final_test_raw <- read.csv("final_test.csv", stringsAsFactors = FALSE,
                           na.strings = "", colClasses = column_types) %>%
  mutate(recalled = as.logical(recalled))

setwd(oldwd)

rm(column_types)
```

```{r tidying}
join_variables <- c("subject", "id", "list")
select_variables <- c(join_variables, "practice", "practice_cue_type")

# Remove subjects with technical problems from the dataset.
subjects <- filter(subjects, subject >= 1)

## Practice Test
test_practice_raw <- test_practice_raw %>%
  inner_join(x = .,
             y = subjects[c("subject","group")],
             by = "subject") %>%
  left_join(x = .,
            y = conditions[select_variables],
            by = join_variables) %>%
  test_tidying()

# Check these fuzzy matches by hand
tp_fuzzy <- filter(tibble::rownames_to_column(test_practice_raw, "row"),
                   !hard_match & fuzzy_match) %>%
   select(row, subject, cue, target, response)


# Final Test
final_test_raw <- final_test_raw %>%
  inner_join(x = .,
             y = subjects[c("subject","group")],
             by = "subject") %>%
  left_join(x = .,
            y = conditions[select_variables],
            by = join_variables) %>%
  test_tidying()

# Check these fuzzy matches by hand
final_fuzzy <- filter(tibble::rownames_to_column(final_test_raw, "row"),
                      !hard_match & fuzzy_match) %>%
   select(row, subject, cue, target, response)

# These are determined by manual inspection
final_test_raw[final_test_raw$subject == 21 & final_test_raw$cue == "comedy",
               'fuzzy_match'] <- FALSE

## Combine practice and final tests into one data frame
tests_raw <- bind_rows(`1`=test_practice_raw, `2`=final_test_raw,
                       .id = "test") %>%
  rename(correct = fuzzy_match) %>%
  mutate(logRT = log(RT),
         test = as.numeric(test)) %>%
  select(subject, group, test, list, trial, practice, practice_cue_type, decided, recalled,
         correct, RT, logRT, pre_typing_lag:post_typing_lag) %>%
  arrange(subject, test, list)

# Mark trials where a remember/don't remember decision was not reached (time out trial) as incorrect
tests_raw$correct[!tests_raw$decided] <- FALSE

rm(tp_fuzzy, final_fuzzy, join_variables, select_variables)
```

```{r acc_and_RT_by_subject}
#### Calculate accuracy for each subject in each condition
acc_by_subject <- tests_raw %>%
  group_by(subject, group, test, practice, practice_cue_type) %>%
  summarise(N_acc_trials = n(),
            N_correct = sum(correct),
            percent_correct = N_correct/N_acc_trials) %>%
  ungroup()

#### Aggregate reaction time measures for each subject in each condition
RT_by_subject <- tests_raw %>%
  filter(decided, recalled == correct) %>%
  group_by(subject, group, test, practice, practice_cue_type, correct) %>%
  summarise(N_RT_trials = n(),
            mean_RT = mean(RT),
            mean_logRT = mean(logRT),
            median_RT = median(RT)) %>%
  ungroup()


```

```{r plotting_scales}
color_scale <- scale_color_discrete("Practice Condition",
                                    labels = c("S.episodic" = "Restudy, Episodic",
                                               "T.episodic" = "Test, Episodic",
                                               "S.semantic" = "Restudy, Semantic",
                                               "T.semantic" = "Test, Semantic",
                                               "N" = "No Practice")
                                    )
x_axis_scale <- scale_x_discrete("Group",
                                 limits = c("immediate","delay"),
                                 labels = c("Immediate", "Delay"),
                                 expand = c(0, .1)
                                 )
```

## Accuracy
```{r acc_means}
acc <- filter(acc_by_subject, test == 2) %>%
  mutate(condition = replace(as.character(interaction(practice, practice_cue_type)),
                             is.na(practice_cue_type),
                             "N")
         ) %>%
  whoppeR::WISEsummary(dependentvars = "percent_correct", idvar = "subject",
                       betweenvars = "group", withinvars = "condition"
                       ) %>%
  rename(percent_correct = percent_correct_mean)
```

```{r acc_means_plot}
acc_plot <- mutate(acc,
                   condition = factor(condition,
                                      levels = c("S.episodic","S.semantic","T.semantic","T.episodic","N")
                                      )
                   ) %>%
  ggplot(aes(x = group, y = percent_correct,
             color = condition, group = condition
             )
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = percent_correct_CI_lower, ymax = percent_correct_CI_upper),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Percent Correct", limits = c(.2, .8),
                     breaks = seq(.2, .8, by = .1)) + 
  color_scale +
  theme_grey(base_size = 16)

print(acc_plot)
```

### lme4::glmer
```{r acc_glmer}
afex::set_sum_contrasts()

acc_data <- mutate(tests_raw,
                   condition = replace(as.character(interaction(practice, practice_cue_type)),
                                       is.na(practice_cue_type),
                                       "N"),
                   condition = factor(condition,
                                      levels = c("S.episodic","S.semantic","T.semantic","T.episodic","N")
                                      ),
                   group = factor(group, levels = c("immediate","delay"))) %>%
  filter(test == 2)

PSOCK_cl <- parallel::makeCluster(parallel::detectCores())

acc_glmer <- mixed(correct ~ group*condition + (1|subject),
                   data = acc_data,
                   method = "LRT",
                   cl = PSOCK_cl,
                   family = binomial,
                   progress = TRUE
                   )

parallel::stopCluster(PSOCK_cl)
summary(acc_glmer$full_model)
```

```{r acc_glmer_contrasts}
# These 2 functions absolutely rely on hard-coding the order of the factor levels in the regressions anlysis. If the factors are for some reason ordered in some other fashion than described in the row names here, these contrasts will not match their labels!
my_contrasts.emmc <- function(...) {
  custom_contrast_matrix <- data.frame(`S.semantic - S.episodic` = c(-1, 1, 0, 0, 0),
                                       `T.semantic - S.semantic` = c(0, -1, 1, 0, 0),
                                       `T.episodic - T.semantic` = c(0, 0, -1, 1, 0),
                                       `T.episodic - S.episodic` = c(-1, 0, 0, 1, 0),
                                       `N - T.episodic` =          c(0, 0, 0, -1, 1),
                                       `N - T.semantic` =          c(0, 0, -1, 0, 1),
                                       `N - S.semantic` =          c(0, -1, 0, 0, 1),
                                       `N - S.episodic` =          c(-1, 0, 0, 0, 1),
                                       row.names = c("S.episodic","S.semantic","T.semantic","T.episodic","N"),
                                       check.names = FALSE
                                       )
  attr(custom_contrast_matrix, "desc") <- "Subset of pairwise comparisions"
  attr(custom_contrast_matrix, "adjust") <- "holm"
  return(custom_contrast_matrix)
}

my_interaction_contrasts.emmc <- function(...) {
  custom_contrast_matrix <- data.frame(`T.semantic - S.semantic` = c(0, -1, 1, 0, 0),
                                       `T.episodic - S.episodic` = c(-1, 0, 0, 1, 0),
                                       `T.episodic - T.semantic` = c(0, 0, -1, 1, 0),
                                       row.names = c("S.episodic","S.semantic","T.semantic","T.episodic","N"),
                                       check.names = FALSE
                                       )
  attr(custom_contrast_matrix, "desc") <- "Subset of pairwise comparisions"
  attr(custom_contrast_matrix, "adjust") <- "holm"
  return(custom_contrast_matrix)
}

acc_glmer_EMM <- emmeans(acc_glmer, specs = c("group", "condition"), type = "response")
acc_glmer_contrasts <- contrast(acc_glmer_EMM, method = my_contrasts.emmc, 
                                by = "group", type ="link", adjust = 'holm')
acc_glmer_interactions <- contrast(acc_glmer_EMM, interaction = c('pairwise', 'my_interaction_contrasts'), 
                                   type ="link", adjust = 'holm')
```

```{r acc_glmer_display}
acc_glmer_EMM_plot <-
  ggplot(as.data.frame(acc_glmer_EMM),
         aes(x = group, y = prob, color = condition, group = condition)
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Percent Correct", limits = c(.1, .9),
                     breaks = seq(.1, .9, by = .1)) +
  color_scale +
  theme_grey(base_size = 16) +
  theme(legend.position = c(.8,.8),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10)) +
  ggtitle("lme4::glmer Model Predictions")

acc_glmer_contrasts_plot <- plot(acc_glmer_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

## Cell means & Contrasts
grid.arrange(acc_glmer_EMM_plot, acc_glmer_contrasts_plot, ncol = 2)

## ANOVA/LRT Table
knitr::kable(nice(acc_glmer), format = 'html',
             caption = paste(attr(acc_glmer[[1]], 'heading'), collapse = ". ")
             ) %>%
  kableExtra::kable_styling(full_width = FALSE, position = 'float_left')

## Contrasts Table
select(as.data.frame(summary(acc_glmer_contrasts)), group, contrast, estimate:p.value) %T>% 
  { cap <<- paste(c("Within-group practice condition comparisons. ", attr(., "mesg")),
                  collapse = " ") } %>%
knitr::kable(format = 'html', align = 'crccccc', digits = c(0,0,3,3,3,3,4),
             caption = cap) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  kableExtra::collapse_rows(columns = 1)

## Interactions of interest
rename(as.data.frame(summary(acc_glmer_interactions)),
       group = group_pairwise, condition = condition_my_interaction_contrasts) %T>%
  { cap <<- paste(c("Interaction contrasts. ",  attr(., "mesg")),
                  collapse = " ")} %>%
  mutate(condition = cell_spec(condition,
                               color = ifelse(p.value < .05, "red", "#333333"),
                               format = 'html'
                               )
         ) %>%  
  knitr::kable(format = "html", digits = c(0,0,3,3,3,3,4),
               caption = cap, escape = FALSE) %>%
  kableExtra::kable_styling(full_width = FALSE)
```

### rstanarm::stan_glmer
#### Default weakly informative priors
```{r acc_rstan_glmer_uninformed}
acc_rstan_glmer_uninformed <- stan_glmer(correct ~ group*condition + (1|subject),
                                         data = acc_data,
                                         family = binomial(link = "logit"),
                                         contrasts = list(group = 'contr.sum',
                                                          condition = 'contr.sum'),
                                         sparse = TRUE,
                                         seed = 124, iter = 3000
                                         )

summary(acc_rstan_glmer_uninformed,
        pars = names(fixef(acc_rstan_glmer_uninformed)),
        probs = c(.025, .5, .975), digits = 3)
```

```{r acc_rstan_glmer_uninformed_contrasts, dependson='acc_stan_glmer_uninformed'}
acc_rstan_glmer_uninformed_EMM <- emmeans(acc_rstan_glmer_uninformed,
                                          specs = c("group", "condition"),
                                          type = "response")

acc_rstan_glmer_uninformed_contrasts <- contrast(acc_rstan_glmer_uninformed_EMM, 'my_contrasts',
                                                 by = "group", type ="link")

acc_rstan_glmer_uninformed_interactions <- contrast(acc_rstan_glmer_uninformed_EMM,
                                                    interaction = c('pairwise', 'my_interaction_contrasts'),
                                                    type ="link", adjust = 'holm')
```

```{r acc_rstan_glmer_uninformed_display, dependson='acc_rstan_glmer_uninformed_contrasts'}
acc_rstan_glmer_uninformed_EMM_plot <-
  ggplot(as.data.frame(acc_rstan_glmer_uninformed_EMM),
         aes(x = group, y = prob, color = condition, group = condition)
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = lower.HPD, ymax = upper.HPD),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Percent Correct", limits = c(.1, .9),
                     breaks = seq(.1, .9, by = .1)) +
  color_scale +
  theme_grey(base_size = 16) +
  theme(legend.position = c(.8,.8),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10)) +
  ggtitle("rstan_glmer Model Predictions\n(Weak Priors)")

acc_rstan_glmer_uninformed_contrasts_plot <-
  plot(acc_rstan_glmer_uninformed_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

grid.arrange(acc_rstan_glmer_uninformed_EMM_plot,
             acc_rstan_glmer_uninformed_contrasts_plot,
             ncol = 2)
## Interactions of Interest
rename(as.data.frame(summary(acc_rstan_glmer_uninformed_interactions)),
       group = group_pairwise, condition = condition_my_interaction_contrasts) %T>%
       { cap <<- paste(c("HDI for interaction contrast.", attr(., "mesg")),
                         collapse = " ") } %>%
  knitr::kable(format = "html", digits = c(0,0,3,3,3,3,4),
               caption = cap ) %>%
  kableExtra::kable_styling(full_width = FALSE)
```


#### Informed priors
```{r acc_rstan_glmer_informed-priors}
coef_priors = list("group1" = c('mean' = 0.837, 'sd' = .131),
                   "condition1" = c('mean' = 0.635, 'sd' = 0.052),
                   "condition2" = c('mean' = 0.252, 'sd' = 0.042),
                   "condition3" = c('mean' = 0.142, 'sd' = 0.041),
                   "condition4" = c('mean' = -0.008, 'sd' = 0.047),
                   "group1:condition1" = c('mean' = 0.406, 'sd' = 0.052),
                   "group1:condition2" = c('mean' = 0, 'sd' = 0.042),
                   "group1:condition3" = c('mean' = 0, 'sd' = 0.041),
                   "group1:condition4" = c('mean' = -0.354, 'sd' = 0.047))

acc_rstan_glmer <- stan_glmer(correct ~ group*condition + (1|subject),
                              data = acc_data,
                              family = binomial(link = "logit"),
                              contrasts = list(group = 'contr.sum',
                                               condition = 'contr.sum'),
                              prior_intercept = normal(0.268, 5 * .131, autoscale = FALSE),
                              prior = normal(location = sapply(coef_priors, `[[`, "mean"),
                                             scale = 5 * sapply(coef_priors, `[[`, "sd"),
                                             autoscale = FALSE
                                             ),
                              sparse = TRUE,
                              seed = 124, iter = 3000)

summary(acc_rstan_glmer, pars = names(fixef(acc_rstan_glmer)),
        probs = c(.025, .5, .975), digits = 3)
```

```{r acc_rstan_glmer_informed-priors_contrasts, dependson='acc_rstan_glmer_informed-priors'}
acc_rstan_glmer_EMM <- emmeans(acc_rstan_glmer,
                               specs = c("group", "condition"),
                               type = "response")

acc_rstan_glmer_contrasts <- contrast(acc_rstan_glmer_EMM, 'my_contrasts',
                                      by = "group", type ="link")

acc_rstan_glmer_interactions <- contrast(acc_rstan_glmer_EMM,
                                         interaction = c('pairwise', 'my_interaction_contrasts'),
                                         type ="link", adjust = 'holm')
```

```{r acc_rstan_glmer_informed-priors_display, dependson='acc_rstan_glmer_informed-priors_contrasts'}
acc_rstan_glmer_EMM_plot <- acc_rstan_glmer_uninformed_EMM_plot %+%
  as.data.frame(acc_rstan_glmer_EMM) +
  ggtitle("rstan_glmer Model Predictions\n(Informative Priors)")

acc_rstan_glmer_contrasts_plot <-
  plot(acc_rstan_glmer_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

grid.arrange(acc_rstan_glmer_EMM_plot,
             acc_rstan_glmer_contrasts_plot,
             ncol = 2)

## Interactions of Interest
rename(as.data.frame(summary(acc_rstan_glmer_interactions)),
       group = group_pairwise, condition = condition_my_interaction_contrasts) %T>%
  { cap <<- paste(c("HDI for interaction contrast.", attr(., "mesg")),
                  collapse = " ") } %>%
  knitr::kable(format = "html", digits = c(0,0,3,3,3,3,4),
               caption = cap ) %>%
  kableExtra::kable_styling(full_width = FALSE)
```

## RT
```{r RT_means}
RT <- filter(RT_by_subject, test == 2, correct) %>%
  mutate(condition = replace(as.character(interaction(practice, practice_cue_type)),
                             is.na(practice_cue_type),
                             "N")
         ) %>%
  whoppeR::WISEsummary(dependentvars = c("mean_RT", "mean_logRT", "median_RT"),
                       idvar = "subject",
                       betweenvars = "group", withinvars = "condition"
                       )
names(RT) <- gsub(pattern = "_mean$", "", names(RT))
```

```{r RT_means_plot}
RT_plot <- mutate(RT,
                  condition = factor(condition,
                                     levels = c("S.episodic","S.semantic","T.semantic","T.episodic","N")
                                     )
                  ) %>%
  ggplot(aes(x = group, y = mean_logRT,
             color = condition, group = condition
             )
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = mean_logRT_CI_lower, ymax = mean_logRT_CI_upper),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Log RT (s)") + 
  color_scale +
  theme_grey(base_size = 16)

print(RT_plot)
```

### lme4::lmer
```{r RT_lmer}
RT_lmer_data <- filter(acc_data, decided, recalled, correct)
RT_lmer <- mixed(logRT ~ group*condition + (condition|subject),
                 data = RT_lmer_data,
                 method = "KR",
                 contrasts = list(group = 'contr.sum',
                                  condition = 'contr.sum'),
                 control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
                 )

RT_lmer_summary <- summary(RT_lmer$full_model, ddf="Kenward-Roger")
print(RT_lmer_summary)
```

```{r RT_lmer_contrasts}
emm_options(pbkrtest.limit = 6000)
RT_lmer_EMM <- emmeans(RT_lmer , specs = c("group", "condition"))
RT_lmer_contrasts <- contrast(RT_lmer_EMM, method = my_contrasts.emmc,
                              by ="group", adjust = 'holm')

```

```{r RT_lmer_display}
RT_lmer_EMM_plot <- 
  ggplot(as.data.frame(RT_lmer_EMM),
         aes(x = group, y = emmean, color = condition, group = condition)
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Log RT (s)") + 
  color_scale +
  guides(color = guide_legend(nrow = 3)) +
  theme_grey(base_size = 16) +
  theme(legend.position = c(.25,.85),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12))
  ggtitle("lme4::lmer Model Predictions")

RT_lmer_contrasts_plot <- plot(RT_lmer_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

grid.arrange(RT_lmer_EMM_plot, RT_lmer_contrasts_plot, ncol = 2)

knitr::kable(nice(RT_lmer), format = 'html',
             caption = paste(attr(RT_lmer[[1]], 'heading'), collapse=" ")) %>%
  kableExtra::kable_styling(full_width = FALSE, position = 'float_left')

select(as.data.frame(summary(RT_lmer_contrasts)), group, contrast, estimate:p.value) %T>%
  {cap <<- paste(c("Within-group practice condition comparisons.", attr(., 'mesg')),
                 collapse = " ")} %>%
  knitr::kable(format = 'html', align = 'crccccc', digits = c(0,0,3,3,3,3,4),
             caption = cap) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  kableExtra::collapse_rows(columns = 1)
```

### rstanarm::stan_lmer
```{r RT_rstan_lmer_uninformed}
RT_rstan_lmer_uninformed <- stan_lmer(logRT ~ group*condition + (1|subject),
                                      data = RT_lmer_data,
                                      contrasts = list(group = 'contr.sum',
                                                       condition = 'contr.sum'),
                                      seed = 123,
                                      adapt_delta = .999,
                                      sparse = TRUE,
                                      iter = 3000)

summary(RT_rstan_lmer_uninformed,
        pars = names(fixef(RT_rstan_lmer_uninformed)),
        probs = c(.025, .5, .975), digits = 3)
```

```{r RT_rstan_lmer_uninformed_contrasts, dependson=c('RT_rstan_lmer_uninformed')}
RT_rstan_lmer_uninformed_EMM <- emmeans(RT_rstan_lmer_uninformed, ~ group * condition)

RT_rstan_lmer_uninformed_contrasts <- contrast(RT_rstan_lmer_uninformed_EMM, 'my_contrasts',
                                               by = "group", adjust = 'holm')

RT_rstan_lmer_uninformed_interactions <- contrast(RT_rstan_lmer_uninformed_EMM,
                                                  interaction = c('pairwise', 'pairwise'),
                                                  adjust = 'holm')
```

```{r RT_rstan_lmer_uninformed_display, dependson='RT_rstan_lmer_uninformed_contrasts'}
RT_rstan_lmer_uninformed_EMM_plot <-
  ggplot(as.data.frame(RT_rstan_lmer_uninformed_EMM),
         aes(x = group, y = emmean, color = condition, group = condition)
         ) +
  geom_point(size = 2, position = position_dodge(.1)) +
  geom_line(position = position_dodge(.1)) +
  geom_errorbar(aes(ymin = lower.HPD, ymax = upper.HPD),
                width = .15,
                position = position_dodge(.1)) +
  x_axis_scale +
  scale_y_continuous("Log RT (s)") + 
  color_scale +
  theme_grey(base_size = 16) +
  guides(color = guide_legend(nrow = 3)) +
  theme(legend.position = c(.25,.85),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12)) +
  ggtitle("rstan_lmer Model Predictions\n(Weak Priors)")

RT_rstan_lmer_uninformed_contrasts_plot <-
  plot(RT_rstan_lmer_uninformed_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

grid.arrange(RT_rstan_lmer_uninformed_EMM_plot,
             RT_rstan_lmer_uninformed_contrasts_plot,
             ncol = 2)

## Interactions of Interest
rename(as.data.frame(summary(RT_rstan_lmer_uninformed_interactions)),
       group = group_pairwise, condition = condition_pairwise) %T>%
  { cap <<- paste(c("HDI for interactions.", attr(., "mesg")),
                  collapse = " ") } %>%
  knitr::kable(format = "html", digits = c(0,0,3,3,3,3,4),
               caption = cap ) %>%
  kableExtra::kable_styling(full_width = FALSE)
```

#### Informed priors
```{r RT_rstan_lmer_informed-priors}
RT_coef_priors = list("group1" = c('mean' = -.2129, 'sd' = .0021),
                      "condition1" = c('mean' = -.0159, 'sd' = .001),
                      "condition2" = c('mean' = -0.046, 'sd' = .012),
                      "condition3" = c('mean' = -0.046, 'sd' = .012),
                      "condition4" = c('mean' = -.0159, 'sd' = .001),
                      "group1:condition1" = c('mean' = 0.006, 'sd' = .001),
                      "group1:condition2" = c('mean' = 0, 'sd' = .012),
                      "group1:condition3" = c('mean' = 0, 'sd' = .012),
                      "group1:condition4" = c('mean' = -.032, 'sd' = .001))

RT_rstan_lmer <- stan_lmer(logRT ~ group*condition + (1|subject),
                           data = RT_lmer_data,
                           contrasts = list(group = 'contr.sum',
                                            condition = 'contr.sum'),
                           prior_intercept = normal(.638, 5*.0021, autoscale = FALSE),
                           prior = normal(location = sapply(coef_priors, `[[`, "mean"),
                                          scale = 5 * sapply(coef_priors, `[[`, "sd"),
                                          autoscale = FALSE
                                          ),
                           sparse = TRUE,
                           seed = 124,
                           iter = 3000)

summary(RT_rstan_lmer, pars = names(fixef(RT_rstan_lmer)),
        probs = c(.025, .5, .975), digits = 3)
```

```{r RT_rstan_lmer_informed-priors_contrasts, dependson = 'RT_rstan_lmer_informed-priors'}
RT_rstan_lmer_EMM <- emmeans(RT_rstan_lmer,
                             specs = c("group", "condition"),
                             type = "response")

RT_rstan_lmer_contrasts <- contrast(RT_rstan_lmer_EMM, 'my_contrasts',
                                    by = "group", type ="link")

RT_rstan_lmer_interactions <- contrast(RT_rstan_lmer_EMM,
                                       interaction = c('pairwise', 'pairwise'),
                                       type ="link", adjust = 'holm')
```

```{r RT_stan_lmer_informed-priors_display, dependson = c('RT_rstan_lmer_informed-priors_contrasts','RT_rstan_lmer_uninformed_display')}
RT_rstan_lmer_EMM_plot <- RT_rstan_lmer_uninformed_EMM_plot %+%
  as.data.frame(RT_rstan_lmer_EMM) +
  ggtitle("rstan_glmer Model Predictions\n(Informative Priors)")

RT_rstan_lmer_contrasts_plot <- plot(RT_rstan_lmer_contrasts) +
  geom_vline(xintercept = 0) +
  ggtitle("Contrasts")

grid.arrange(RT_rstan_lmer_EMM_plot,
             RT_rstan_lmer_contrasts_plot,
             ncol = 2)

## Interactions of Interest
rename(as.data.frame(summary(RT_rstan_lmer_interactions)),
       group = group_pairwise, condition = condition_pairwise) %T>%
  { cap <<- paste(c("HDI for interaction contrast.", attr(., "mesg")),
                  collapse = " ") } %>%
  knitr::kable(format = "html", digits = c(0,0,3,3,3,3,4),
               caption = cap ) %>%
  kableExtra::kable_styling(full_width = FALSE)
```

# Questions
- Are differences between semantic-associate retrieval pratice and semantic-associate restudy due to retrieving the wrong thing, e.g., a *different* semantic associate?
